export const GET_NFT_REQUEST = "GET_NFT_REQUEST";
export const GET_NFT_SUCCESS = "GET_NFT_SUCCESS";
export const GET_NFT_FAILURE = "GET_NFT_FAILURE";

export const UPDATE_NFT_REQUEST = "UPDATE_NFT_REQUEST";
export const UPDATE_NFT_SUCCESS = "UPDATE_NFT_SUCCESS";
export const UPDATE_NFT_FAILURE = "UPDATE_NFT_FAILURE";

export const FETCH_TOP_5_NFTS_REQUEST = 'FETCH_TOP_5_NFTS_REQUEST';
export const FETCH_TOP_5_NFTS_SUCCESS = 'FETCH_TOP_5_NFTS_SUCCESS';
export const FETCH_TOP_5_NFTS_FAILURE = 'FETCH_TOP_5_NFTS_FAILURE';

export const GET_ALL_NFTS_REQUEST = 'GET_ALL_NFTS_REQUEST';
export const GET_ALL_NFTS_SUCCESS = 'GET_ALL_NFTS_SUCCESS';
export const GET_ALL_NFTS_FAILURE = 'GET_ALL_NFTS_FAILURE';



  