export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_UPDATE_DATA = 'USER_UPDATE_DATA';

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";

export const USER_PIC_REQUEST = "USER_PIC_REQUEST";
export const USER_PIC_SUCCESS = "USER_PIC_SUCCESS";
export const USER_PIC_FAIL = "USER_PIC_FAIL";

export const GET_ALL_NFTS_REQUEST = "GET_ALL_NFTS_REQUEST";
export const GET_ALL_NFTS_SUCCESS = "GET_ALL_NFTS_SUCCESS";
export const GET_ALL_NFTS_FAILURE = "GET_ALL_NFTS_FAILURE";